# Pandas Exercise: IMDB Top 250 Movies

## üóÑÔ∏è Data
The dataset we will be using contains the top 250 movies from IMDB as of 2022. This dataset can be found on [Kaggle](https://www.kaggle.com/datasets/rajugc/imdb-top-250-movies-dataset), but you can also access it directly from [this link](https://parsa-abbasi.github.io/slides/pandas/imdb_top_250_movies.csv).

The dataset contains the following columns:
- `rank`: The rank of the movie on IMDB
- `name`: The name of the movie
- `year`: The year the movie was released
- `rating`: The rating of the movie on IMDB
- `genre`: The genre of the movie
- `certificate`: The certificate of the movie (e.g. PG-13, R, etc.)
- `run_time`: The runtime of the movie in a string format (e.g. 1h 30m)
- `tagline`: The tagline of the movie
- `budget`: The budget of the movie in dollars
- `box_office`: Total box office collection across the world in dollars
- `cast`: All casts of the movie
- `directors`: The director(s) of the movie
- `writers`: The writer(s) of the movie

The missing values in the dataset are represented as `<NA>` and `Not Available`.

In [1]:
import pandas as pd
imdb = pd.read_csv('https://parsa-abbasi.github.io/slides/pandas/imdb_top_250_movies.csv', index_col='rank', na_values=['<NA>', 'Not Available'])

In [2]:
imdb.shape

(250, 12)

In [3]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250 entries, 1 to 250
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         250 non-null    object
 1   year         250 non-null    int64
 2   rating       250 non-null    float64
 3   genre        250 non-null    object
 4   certificate  249 non-null    object
 5   run_time     249 non-null    object
 6   tagline      250 non-null    object
 7   budget       211 non-null    object
 8   box_office   220 non-null    object
 9   casts        250 non-null    object
 10  directors    250 non-null    object
 11  writers      250 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 25.4+ KB

## Display Top 10 Highest-Rated Movies

In [4]:
imdb.head(10)

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
6,Schindler's List,1993,9.0,"Biography,Drama,History",R,3h 15m,"Whoever saves one life, saves the world entire.",22000000,322161245,"Liam Neeson,Ralph Fiennes,Ben Kingsley,Carolin...",Steven Spielberg,"Thomas Keneally,Steven Zaillian"
7,The Lord of the Rings: The Return of the King,2003,9.0,"Action,Adventure,Drama",PG-13,3h 21m,The eye of the enemy is moving.,94000000,1146457748,"Elijah Wood,Viggo Mortensen,Ian McKellen,Orlan...",Peter Jackson,"J.R.R. Tolkien,Fran Walsh,Philippa Boyens"
8,Pulp Fiction,1994,8.9,"Crime,Drama",R,2h 34m,Girls like me don't make invitations like this...,8000000,213928762,"John Travolta,Uma Thurman,Samuel L. Jackson,Br...",Quentin Tarantino,"Quentin Tarantino,Roger Avary"
9,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,"Action,Adventure,Drama",PG-13,2h 58m,The Legend Comes to Life,93000000,898204420,"Elijah Wood,Ian McKellen,Orlando Bloom,Sean Be...",Peter Jackson,"J.R.R. Tolkien,Fran Walsh,Philippa Boyens"
10,"The Good, the Bad and the Ugly",1966,8.8,"Adventure,Western",Approved,2h 58m,They formed an alliance of hate to steal a for...,1200000,25253887,"Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo ...",Sergio Leone,"Luciano Vincenzoni,Sergio Leone,Agenore Incrocci"

## Number of Movies Released After 2020
Find the number of movies released after 2020 and assign it to the variable `num_movies_after_2020`.

In [5]:
num_movies_after_2020 = imdb[imdb['year'] > 2020].shape[0]
print('The number of movies released after 2020 is', num_movies_after_2020)

The number of movies released after 2020 is 3

## Movies Starring Leonardo DiCaprio
Filter the dataset to only include movies starring Leonardo DiCaprio and assign the result to the variable `leo_movies`.

In [6]:
leo_movies = imdb[imdb['casts'].str.contains('Leonardo DiCaprio')]
leo_movies

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
14,Inception,2010,8.8,"Action,Adventure,Sci-Fi",PG-13,2h 28m,Your mind is the scene of the crime,160000000,836848102,"Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot ...",Christopher Nolan,Christopher Nolan
39,The Departed,2006,8.5,"Crime,Drama,Thriller",R,2h 31m,Lies. Betrayal. Sacrifice. How far will you ta...,90000000,291480452,"Leonardo DiCaprio,Matt Damon,Jack Nicholson,Ma...",Martin Scorsese,"William Monahan,Alan Mak,Felix Chong"
55,Django Unchained,2012,8.4,"Drama,Western",R,2h 45m,"Life, liberty and the pursuit of vengeance.",100000000,426074373,"Jamie Foxx,Christoph Waltz,Leonardo DiCaprio,K...",Quentin Tarantino,Quentin Tarantino
132,The Wolf of Wall Street,2013,8.2,"Biography,Comedy,Crime",R,3h,Earn. Spend. Party.,100000000,406878233,"Leonardo DiCaprio,Jonah Hill,Margot Robbie,Mat...",Martin Scorsese,"Terence Winter,Jordan Belfort"
142,Shutter Island,2010,8.2,"Mystery,Thriller",R,2h 18m,Someone is missing.,80000000,294805697,"Leonardo DiCaprio,Emily Mortimer,Mark Ruffalo,...",Martin Scorsese,"Laeta Kalogridis,Dennis Lehane"
173,Catch Me If You Can,2002,8.1,"Biography,Crime,Drama",PG-13,2h 21m,The true story of a real fake.,NaN,NaN,"Leonardo DiCaprio,Tom Hanks,Christopher Walken...",Steven Spielberg,"Jeff Nathanson,Frank Abagnale Jr.,Stan Redding"

## Average Runtime of Movies
Compute the average runtime of movies (in minutes) and assign it to the variable `avg_runtime`.

Let's take a look at runtime of movies. We can see that the runtime is in a string format, so we will need to convert it to a numeric format.

In [7]:
imdb['run_time'].unique()

array(['2h 22m', '2h 55m', '2h 32m', '3h 22m', '1h 36m', '3h 15m',
       '3h 21m', '2h 34m', '2h 58m', '2h 19m', '2h 59m', '2h 28m',
       '2h 4m', '2h 16m', '2h 25m', '2h 13m', '2h 7m', '3h 27m', '2h 10m',
       '1h 58m', '2h 49m', '1h 56m', '3h 9m', '2h 1m', '2h 17m', '2h 5m',
       '2h 30m', '1h 49m', '2h 12m', '1h 50m', '1h 28m', '2h 35m',
       '1h 59m', '2h 31m', '1h 46m', '1h 42m', '1h 29m', '1h 52m',
       '1h 27m', '2h 45m', '1h 57m', '2h 27m', '1h 53m', '1h 55m',
       '1h 38m', '2h 26m', '2h 29m', '2h 2m', '1h 35m', '2h 44m', '2h',
       '2h 33m', '2h 40m', '1h 45m', '1h 21m', nan, '3h 1m', '2h 14m',
       '3h 49m', '2h 6m', '2h 50m', '1h 43m', '2h 23m', '2h 11m',
       '1h 48m', '1h 39m', '3h 38m', '2h 8m', '1h 47m', '2h 9m', '2h 3m',
       '1h 54m', '2h 18m', '2h 36m', '2h 41m', '2h 20m', '1h 8m',
       '1h 37m', '3h', '2h 42m', '2h 38m', '2h 15m', '1h 31m', '2h 52m',
       '1h 51m', '1h 40m', '3h 58m', '1h 33m', '1h 26m', '2h 21m',
       '1h 41m', '3h 32m', '1h 7m', '3h 3m', '3h 5m', '45m', '1h 32m',
       '1h 20m', '1h 23m', '1h 34m', '1h 30m', '3h 11m'], dtype=object)

As you can see, there are different formats for the runtime like:
- `2h 22m`
- `2h`
- `45m`

So we should handle all of these cases.

In [8]:
def clean_runtime(runtime):
    if pd.isna(runtime):
        return runtime
    hours = 0
    if 'h' in runtime:
        hours = int(runtime.split('h')[0])
    minutes = 0
    if 'm' in runtime:
        minutes = int(runtime.split('m')[0].split('h')[-1])
    return hours * 60 + minutes

imdb['run_time'] = imdb['run_time'].apply(clean_runtime)
imdb['run_time']

rank
1      142.0
2      175.0
3      152.0
4      202.0
5       96.0
       ...
246    146.0
247    142.0
248     90.0
249    191.0
250    181.0
Name: run_time, Length: 250, dtype: float64

In [9]:
avg_runtime = imdb['run_time'].mean()
print('The average runtime of movies in the dataset is', avg_runtime)
print('Which is equal to', int(avg_runtime / 60), 'hours and', int(avg_runtime % 60), 'minutes')

The average runtime of movies in the dataset is 129.05220883534136
Which is equal to 2 hours and 9 minutes

## Most Common Genre
Find the most common genre and put it name in the variable `most_common_genre` and the number of movies in that genre in the variable `most_common_genre_count`.

In [10]:
imdb['genre'] = imdb['genre'].apply(lambda x: x.split(','))

In [11]:
imdb.head()

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,[Drama],R,142.0,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
2,The Godfather,1972,9.2,"[Crime, Drama]",R,175.0,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,The Dark Knight,2008,9.0,"[Action, Crime, Drama]",PG-13,152.0,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
4,The Godfather Part II,1974,9.0,"[Crime, Drama]",R,202.0,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
5,12 Angry Men,1957,9.0,"[Crime, Drama]",Approved,96.0,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose

The `explode` function can be used to split the values in a column into multiple rows.

In [12]:
flat_list = imdb['genre'].explode()
counts = flat_list.value_counts()
most_common_genre = counts.index[0]
most_common_genre_count = counts[0]
print('The most common genre is', most_common_genre, 'with', most_common_genre_count, 'movies')

The most common genre is Drama with 177 movies

## Which movie has the longest runtime?
Find the movie with the longest runtime and put its name in the variable `longest_runtime_movie` and its runtime (in minutes) in the variable `longest_runtime`.

In [13]:
longest_runtime = imdb['run_time'].max()
longest_runtime_movie = imdb[imdb['run_time'] == longest_runtime]['name'].values[0]
print('The longest runtime movie is', longest_runtime_movie, 'with a runtime of', int(longest_runtime / 60), 'hours and', int(longest_runtime % 60), 'minutes')

The longest runtime movie is Gone with the Wind with a runtime of 3 hours and 58 minutes

## Which movie has the highest box office collection?

Find the movie with the highest box office collection and assign its name to the variable `highest_box_movie` and its box office collection to the variable `highest_box_value`.

In [14]:
imdb['box_office'].unique()

array(['28884504', '250341816', '1006234167', '47961919', '955',
       '322161245', '1146457748', '213928762', '898204420', '25253887',
       '678226465', '101209702', '947944270', '836848102', '538375067',
       '467222728', '47036784', '109114817', '327333559', '346258',
       '8574081', '272742922', '30680793', '482349603', '773867216',
       '230098753', '286801374', '775398007', '520881154', '383336762',
       '355822319', '120072577', '32052925', '262676096', '19569225',
       '968511805', '503162313', '23875127', '291480452', '23341568',
       '109676311', '49396747', '4626532', '516962', nan, '426588510',
       '463618', '5435024', '37034579', '13019063', '106285522', '50419',
       '104880868', '40047078', '426074373', '389925971', '521311890',
       '77356942', '300073', '5252', '47335804', '970263', '2052415039',
       '7693', '131060248', '356296601', '9523464', '1081169825',
       '15421226', '321457747', '52066791', '814337054', '394436586',
       '1074458282', '213216216', '11487676', '2799439100', '170005875',
       '5473337', '60262836', '2000288', '7390108', '1067316101',
       '475106177', '74036715', '65889846', '2913644', '1645133', '35566',
       '45720631', '142319', '7798146', '96302', '174122191', '18778738',
       '26960374', '14651', '46358827', '1488732821', '65884703',
       '6788659', '599146', '187436818', '156000000', '735099102',
       '22926076', '1349711', '28570902', '126216940', '141603197',
       '83557872', '474171806', '436655', '21897373', '384479940',
       '92181574', '15000000', '373672993', '41960', '195088', '24427162',
       '151052', '406878233', '321752656', '12180', '116112375',
       '4164283', '83862032', '264118201', '76182388', '159167799',
       '672806432', '294805697', '316791257', '1109802321', '46808',
       '5014000', '1940906', '228178', '171627434', '1921847111',
       '180906076', '81379', '19632715', '941637960', '26023860',
       '29225935', '23402427', '134686457', '402382193', '3753929',
       '858848019', '31207', '237536126', '162861289', '27200000',
       '16767475', '122126687', '23308615', '60611975', '269958228',
       '216763646', '41722424', '29328', '5987386', '187733202',
       '1342359942', '910000 (estimated)', '74437720', '173082189',
       '60418', '750000 (estimated)', '1226507', '49074379', '199632',
       '180563636', '1098', '1166717', '144738', '415261382', '311212',
       '1740429', '494879471', '35401758', '579707738', '476512065',
       '235860116', '46969409', '33882243', '225508210', '117250402',
       '138545632', '623726085', '98690254', '78371200', '619179950',
       '52287414', '96983009', '23690757', '56675895', '25637669',
       '135342', '71108591', '23661347', '441306145', '631607053',
       '962002', '654264015', '800000 (estimated)', '20908467', '72275',
       '67', '127244', '159428329', '11477', '20745728', '23335817',
       '216639112', '14480', '52767889', '424208848'], dtype=object)

In [15]:
# Remove the (estimated) part from the box office column
imdb['box_office'] = imdb['box_office'].str.replace('(estimated)', '', regex=False)

In [16]:
# Cast the box office column to float
imdb['box_office'] = imdb['box_office'].astype('float')

In [17]:
highest_bo_movie_idx = imdb['box_office'].idxmax()
highest_box_movie = imdb.loc[highest_bo_movie_idx, 'name']
highest_box_value = imdb.loc[highest_bo_movie_idx, 'box_office']
print('The highest grossing movie is', highest_box_movie, 'with a box office of', highest_box_value)

The highest grossing movie is Avengers: Endgame with a box office of 2799439100.0

# Which movies were directed by one of their writers?

Extract the movies that were directed by one of their writers.

In [18]:
def check_writer_director(x):
    writers = x['writers'].split(',')
    directors = x['directors'].split(',')
    for writer in writers:
        if writer in directors:
            return True
    return False

imdb.loc[imdb.apply(check_writer_director, axis=1)]

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,[Drama],R,142.0,Fear can hold you prisoner. Hope can set you f...,25000000,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
2,The Godfather,1972,9.2,"[Crime, Drama]",R,175.0,An offer you can't refuse.,6000000,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,The Dark Knight,2008,9.0,"[Action, Crime, Drama]",PG-13,152.0,Why So Serious?,185000000,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
4,The Godfather Part II,1974,9.0,"[Crime, Drama]",R,202.0,All the power on earth can't change destiny.,13000000,4.796192e+07,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
8,Pulp Fiction,1994,8.9,"[Crime, Drama]",R,154.0,Girls like me don't make invitations like this...,8000000,2.139288e+08,"John Travolta,Uma Thurman,Samuel L. Jackson,Br...",Quentin Tarantino,"Quentin Tarantino,Roger Avary"
...,...,...,...,...,...,...,...,...,...,...,...,...
243,Persona,1966,8.1,"[Drama, Thriller]",Not Rated,83.0,A new film by Ingmar Bergman,NaN,NaN,"Bibi Andersson,Liv Ullmann,Margaretha Krook,Gu...",Ingmar Bergman,Ingmar Bergman
245,The Iron Giant,1999,8.1,"[Animation, Action, Adventure]",PG,86.0,Some secrets are too huge to hide,70000000,2.333582e+07,"Eli Marienthal,Harry Connick Jr.,Jennifer Anis...",Brad Bird,"Tim McCanlies,Brad Bird,Ted Hughes"
246,The Help,2011,8.1,[Drama],PG-13,146.0,Change begins with a whisper.,25000000,2.166391e+08,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
247,Dersu Uzala,1975,8.2,"[Adventure, Biography, Drama]",G,142.0,There is man and beast at nature's mercy. Ther...,4000000,1.448000e+04,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
248,Aladdin,1992,8.0,"[Animation, Adventure, Comedy]",G,90.0,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"

# Save the dataset to a JSON file
First convert each column with comma-separated values to a list of strings. Then save the dataset to a `JSON` file.

In [19]:
imdb['casts'] = imdb['casts'].apply(lambda x: x.split(','))
imdb['directors'] = imdb['directors'].apply(lambda x: x.split(','))
imdb['writers'] = imdb['writers'].apply(lambda x: x.split(','))

In [20]:
imdb.head(3)

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,[Drama],R,142.0,Fear can hold you prisoner. Hope can set you f...,25000000,2.888450e+07,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will...",[Frank Darabont],"[Stephen King, Frank Darabont]"
2,The Godfather,1972,9.2,"[Crime, Drama]",R,175.0,An offer you can't refuse.,6000000,2.503418e+08,"[Marlon Brando, Al Pacino, James Caan, Diane K...",[Francis Ford Coppola],"[Mario Puzo, Francis Ford Coppola]"
3,The Dark Knight,2008,9.0,"[Action, Crime, Drama]",PG-13,152.0,Why So Serious?,185000000,1.006234e+09,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...",[Christopher Nolan],"[Jonathan Nolan, Christopher Nolan, David S. G..."

In [22]:
imdb.to_json('imdb_top_250.json', orient='records')